### ISSUE TITLE
Port over to conda

### ISSUE THREAD

**Issue by tnigon** [cgevans/scikits-bootstrap#24]
Hi, just wondering if it would be possible to get this package on the Anaconda Cloud platform. I have a package that I'd like to put onto Anaconda Cloud, but I can only do so if all dependencies are also available.

I just looked into uploading myself, but ran into a roadblock due to the [pyerf](https://pypi.org/project/pyerf/#description) dependency. In looking at the code, I see it is only used twice - is there an easy way to remove this pyerf dependency and use another library that seems to be more active? Otherwise, my solution would be to upload the pyerf package to Anaconda Cloud, then scikits.bootstrap, then my package. Let me know where you're at on this - thanks!

**Comment by cgevans** [comment]
Hmmm... this is the situation on that dependency:

The BCA and ABC methods need the error function and inverse error function.  There are implementations of these in scipy, but scipy is a very large and non-pure-python dependency that isn't always easy to install, so I switched to using pyerf instead.  Pyerf is very small (around 350 lines of code) and pure Python, so should always be easy to install.  Scipy uses C implementations of the error function, but scikits-bootstrap doesn't use them enough to matter.

On the other hand, since pyerf is essentially "done" (it's just standard implementations of a few mathematical functions), it doesn't seem to have much in the way of active work going on around it, and isn't as readily available on cloud platforms as scipy.

So there are a few options:

- I could look into putting pyerf on Anaconda Cloud: I haven't used it before, so I'm not quite sure what is involved.
- I could try to arrange something such that scikits-bootstrap could use either pyerf or scipy; this would add some complexity to dependencies, however.
- I could add implementations of the error function and its inverse directly to scikits-bootstrap, and remove the dependency entirely.  However, as pyerf is GPLv3 and scikits-bootstrap is modified BSD, I can't just include the code from there.

**Comment by tnigon** [comment]
Thanks for the quick response - I am leaning towards the option to getting pyerf onto Anaconda Cloud. Cool if I start that process?

I can also take care of getting scikits.bootstrap on Anaconda Cloud if you'd like. I will add you as a "maintainer" (along with myself) - I may need you to drop a comment when this process begins, but I will let you know on this issue thread.

**Comment by cgevans** [comment]
Yes, that would be great; thank you.

**Comment by tnigon** [comment]
I  have started the process for pyerf. It may take up to a day for it to go through before I can begin with scikits.bootstrap. Thanks!

**Comment by tnigon** [comment]
PyErf was just [merged into the conda-forge channel](https://github.com/conda-forge/staged-recipes/pull/10911), and I have initiated the process for scikits-bootstrap. There is a [conda-forge pull request](https://github.com/conda-forge/staged-recipes/pull/10911) for scikits-bootstrap. Please go to this pull request and create a comment saying you are willing to be listed as a maintainer. Thanks!

**Comment by cgevans** [comment]
I've just done that.  Thank you for arranging this.

**Comment by cgevans** [comment]
Closing per merge of https://github.com/conda-forge/staged-recipes/pull/10911
