### ISSUE TITLE
The jacknife procedure can lead to exceptions

### ISSUE THREAD

**Issue by cpennington** [cgevans/scikits-bootstrap#6]
It's possible for `a` in the `bca` method to end up as `NaN`, which causes cascading errors (resulting in an exception at `stats[nvals]` in my test case). This can happen if the measured statistic is identical for all jacknife samples (so that `jmean - jstat` returns an array of `0`s). This happened for me when I was measuring percentile data.

Adding jitter to the input data "fixes" the issue.

**Comment by cgevans** [comment]
Hmm... that's a tricky thing to fix. I'm reluctant to add jitter, though dealing with np.all(jmean-jstat==0) is something that should probably be done. I'll have to look at how the R package deals with it.

**Comment by cpennington** [comment]
Yeah, I wouldn't want to have jitter added by default. It was just my workaround until this issue can be resolved.

**Comment by katastrofa999** [comment]
Hi,

I have the same problem, it can be reproduced like that:

import scikits.bootstrap
import numpy as np
x = np.zeros([100,1])
scikits.bootstrap.ci(x, np.mean, alpha=0.05, n_samples=100, method='bca')

Gives:
/usr/lib/python2.7/site-packages/scikits/bootstrap/bootstrap.py:202: InstabilityWarning: Some values used top 10 low/high samples; results may be unstable.
  warnings.warn("Some values used top 10 low/high samples; results may be unstable.", InstabilityWarning)
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-24-0e54284e856f> in <module>()
----> 1 scikits.bootstrap.ci(x, np.mean, alpha=0.05, n_samples=100)

/usr/lib/python2.7/site-packages/scikits/bootstrap/bootstrap.pyc in ci(data, statfunction, alpha, n_samples, method, output, epsilon, multi)
    205         if nvals.ndim == 1:
    206             # All nvals are the same. Simple broadcasting
--> 207             return stat[nvals]
    208         else:
    209             # Nvals are different for each data point. Not simple broadcasting.

IndexError: index -9223372036854775808 is out of bounds for axis 1 with size 100

Using method='pi' gives correct confidence interval, so the error is somewhere here in bootstrap.py:
    elif method == 'bca':

        # The value of the statistic function applied just to the actual data.
        ostat = statfunction(*tdata)

        # The bias correction value.
        z0 = norm.ppf( ( 1.0*np.sum(stat < ostat, axis=0)  ) / n_samples )

        # Statistics of the jackknife distribution
        jackindexes = jackknife_indexes(tdata[0])
        jstat = [statfunction(*(x[indexes] for x in tdata)) for indexes in jackindexes]
        jmean = np.mean(jstat,axis=0)

        # Acceleration value
        a = np.sum( (jmean - jstat)**3, axis=0 ) / ( 6.0 * np.sum( (jmean - jstat)**2, axis=0)**1.5 )

        zs = z0 + norm.ppf(alphas).reshape(alphas.shape+(1,)*z0.ndim)

        avals = norm.cdf(z0 + zs/(1-a*zs))

It seems that avals is being set to array([ nan,  nan]), and then we have nvals being set to array([-9223372036854775808, -9223372036854775808]), because

np.round(np.nan).astype(int) == -9223372036854775808

So I would investigate why avals is NaN. I suspect this line:

a = np.sum( (jmean - jstat)**3, axis=0 ) / ( 6.0 * np.sum( (jmean - jstat)**2, axis=0)**1.5 )

if jstat == const, np.sum( (jmean - jstat)**3, axis=0 ) == 0 and np.sum( (jmean - jstat)**2, axis=0) == 0. Then we have 0.0/0.0 give NaN. The code should check for this e.g. by checking the value of np.sum( (jmean - jstat)**2, axis=0) and calculate a by a limit. I didn't have the time to check what this limit should be, but will do so in short time (I found this package useful at work and would like it to be fixed).

Thanks for the good work! scikits.bootstrap is very useful.

**Comment by katastrofa999** [comment]
PS. A little thinking about it let me realize that such a limit for a does not exist, because it depends on the type of distribution of values in jstat. E.g. if jstat contains N values +E > 0 and M values -E < 0, then the limit of np.sum( (jmean - jstat)3, axis=0 ) / ( 6.0 * np.sum( (jmean - jstat)2, axis=0)**1.5 ) for E -> 0 is

(N-M) / sqrt(M*N*(M+N)) / 6

hence non-universal. I think the code should either throw an exception at this point or (optionally?) fall back to method = 'pi'.

**Comment by cgevans** [comment]
It looks like the best thing to do is to throw a clear exception at this point. The problem with this sort of data is that the BCa coefficients end up being undefined, so BCa intervals aren't really defined. The R boot package throws errors in this situation; the R bootstrap package (from the Efron book) returns NaN values. Clear error messages that explain what's going on and what to do are called for, I think.

The question is: we've been looking at this with things like CIs on the mean of np.zeros(100). Are there some non-trivial examples (eg, not all the same value) where the measured statistic is identical for a jackknife distribution? @cpennington, did you find this with a nontrivial sample, or did it show up when you were looking at a sample with all identical elements?

**Comment by cgevans** [comment]
I've added an exception explaining the problem, and I think that's pretty much all I can do. I suppose when I have time, I'll try to add a reference to Efron or some similar source explaining the problem. @cpennington, if you have any other idea, please let me know.
